// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cases.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCase = `-- name: CreateCase :one
INSERT INTO cases (
    status,
    risk_level
) VALUES (
    $1, $2
)
RETURNING id, status, risk_level, selected_action_id, created_at, updated_at
`

type CreateCaseParams struct {
	Status    string      `json:"status"`
	RiskLevel pgtype.Text `json:"risk_level"`
}

func (q *Queries) CreateCase(ctx context.Context, arg CreateCaseParams) (Case, error) {
	row := q.db.QueryRow(ctx, createCase, arg.Status, arg.RiskLevel)
	var i Case
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.RiskLevel,
		&i.SelectedActionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCase = `-- name: GetCase :one
SELECT id, status, risk_level, selected_action_id, created_at, updated_at
FROM cases
WHERE id = $1
`

func (q *Queries) GetCase(ctx context.Context, id pgtype.UUID) (Case, error) {
	row := q.db.QueryRow(ctx, getCase, id)
	var i Case
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.RiskLevel,
		&i.SelectedActionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCases = `-- name: ListCases :many
SELECT id, status, risk_level, selected_action_id, created_at, updated_at
FROM cases
ORDER BY created_at DESC
`

func (q *Queries) ListCases(ctx context.Context) ([]Case, error) {
	rows, err := q.db.Query(ctx, listCases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Case
	for rows.Next() {
		var i Case
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.RiskLevel,
			&i.SelectedActionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCasesByStatus = `-- name: ListCasesByStatus :many
SELECT id, status, risk_level, selected_action_id, created_at, updated_at
FROM cases
WHERE status = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCasesByStatus(ctx context.Context, status string) ([]Case, error) {
	rows, err := q.db.Query(ctx, listCasesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Case
	for rows.Next() {
		var i Case
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.RiskLevel,
			&i.SelectedActionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCaseSelectedAction = `-- name: UpdateCaseSelectedAction :one
UPDATE cases
SET
    selected_action_id = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, status, risk_level, selected_action_id, created_at, updated_at
`

type UpdateCaseSelectedActionParams struct {
	ID               pgtype.UUID `json:"id"`
	SelectedActionID pgtype.UUID `json:"selected_action_id"`
}

func (q *Queries) UpdateCaseSelectedAction(ctx context.Context, arg UpdateCaseSelectedActionParams) (Case, error) {
	row := q.db.QueryRow(ctx, updateCaseSelectedAction, arg.ID, arg.SelectedActionID)
	var i Case
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.RiskLevel,
		&i.SelectedActionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCaseStatus = `-- name: UpdateCaseStatus :one
UPDATE cases
SET
    status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, status, risk_level, selected_action_id, created_at, updated_at
`

type UpdateCaseStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateCaseStatus(ctx context.Context, arg UpdateCaseStatusParams) (Case, error) {
	row := q.db.QueryRow(ctx, updateCaseStatus, arg.ID, arg.Status)
	var i Case
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.RiskLevel,
		&i.SelectedActionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
