// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: corrective_actions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearSelectedCorrectiveActionsByCase = `-- name: ClearSelectedCorrectiveActionsByCase :exec
UPDATE corrective_actions
SET is_selected = false
WHERE case_id = $1
`

func (q *Queries) ClearSelectedCorrectiveActionsByCase(ctx context.Context, caseID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearSelectedCorrectiveActionsByCase, caseID)
	return err
}

const createCorrectiveAction = `-- name: CreateCorrectiveAction :one
INSERT INTO corrective_actions (
    case_id,
    code,
    description,
    action_type,
    expected_loss,
    var_value,
    cvar_value,
    constraints_violated,
    is_selected
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, case_id, code, description, action_type, expected_loss, var_value, cvar_value, constraints_violated, is_selected, created_at
`

type CreateCorrectiveActionParams struct {
	CaseID              pgtype.UUID    `json:"case_id"`
	Code                pgtype.Text    `json:"code"`
	Description         string         `json:"description"`
	ActionType          string         `json:"action_type"`
	ExpectedLoss        pgtype.Numeric `json:"expected_loss"`
	VarValue            pgtype.Numeric `json:"var_value"`
	CvarValue           pgtype.Numeric `json:"cvar_value"`
	ConstraintsViolated []byte         `json:"constraints_violated"`
	IsSelected          bool           `json:"is_selected"`
}

func (q *Queries) CreateCorrectiveAction(ctx context.Context, arg CreateCorrectiveActionParams) (CorrectiveAction, error) {
	row := q.db.QueryRow(ctx, createCorrectiveAction,
		arg.CaseID,
		arg.Code,
		arg.Description,
		arg.ActionType,
		arg.ExpectedLoss,
		arg.VarValue,
		arg.CvarValue,
		arg.ConstraintsViolated,
		arg.IsSelected,
	)
	var i CorrectiveAction
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.Code,
		&i.Description,
		&i.ActionType,
		&i.ExpectedLoss,
		&i.VarValue,
		&i.CvarValue,
		&i.ConstraintsViolated,
		&i.IsSelected,
		&i.CreatedAt,
	)
	return i, err
}

const listCorrectiveActionsByCase = `-- name: ListCorrectiveActionsByCase :many
SELECT id, case_id, code, description, action_type, expected_loss, var_value, cvar_value, constraints_violated, is_selected, created_at
FROM corrective_actions
WHERE case_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCorrectiveActionsByCase(ctx context.Context, caseID pgtype.UUID) ([]CorrectiveAction, error) {
	rows, err := q.db.Query(ctx, listCorrectiveActionsByCase, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CorrectiveAction
	for rows.Next() {
		var i CorrectiveAction
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.Code,
			&i.Description,
			&i.ActionType,
			&i.ExpectedLoss,
			&i.VarValue,
			&i.CvarValue,
			&i.ConstraintsViolated,
			&i.IsSelected,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectCorrectiveAction = `-- name: SelectCorrectiveAction :one
UPDATE corrective_actions
SET is_selected = true
WHERE id = $1
RETURNING id, case_id, code, description, action_type, expected_loss, var_value, cvar_value, constraints_violated, is_selected, created_at
`

func (q *Queries) SelectCorrectiveAction(ctx context.Context, id pgtype.UUID) (CorrectiveAction, error) {
	row := q.db.QueryRow(ctx, selectCorrectiveAction, id)
	var i CorrectiveAction
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.Code,
		&i.Description,
		&i.ActionType,
		&i.ExpectedLoss,
		&i.VarValue,
		&i.CvarValue,
		&i.ConstraintsViolated,
		&i.IsSelected,
		&i.CreatedAt,
	)
	return i, err
}
