// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: decision_trace.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDecisionTrace = `-- name: CreateDecisionTrace :one
INSERT INTO decision_trace (
    case_id,
    step,
    data_snapshot,
    model_version,
    parameters,
    risk,
    expert_decision,
    final_action_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, case_id, step, timestamp, data_snapshot, model_version, parameters, risk, expert_decision, final_action_id, created_at
`

type CreateDecisionTraceParams struct {
	CaseID         pgtype.UUID `json:"case_id"`
	Step           string      `json:"step"`
	DataSnapshot   []byte      `json:"data_snapshot"`
	ModelVersion   pgtype.Text `json:"model_version"`
	Parameters     []byte      `json:"parameters"`
	Risk           []byte      `json:"risk"`
	ExpertDecision []byte      `json:"expert_decision"`
	FinalActionID  pgtype.UUID `json:"final_action_id"`
}

func (q *Queries) CreateDecisionTrace(ctx context.Context, arg CreateDecisionTraceParams) (DecisionTrace, error) {
	row := q.db.QueryRow(ctx, createDecisionTrace,
		arg.CaseID,
		arg.Step,
		arg.DataSnapshot,
		arg.ModelVersion,
		arg.Parameters,
		arg.Risk,
		arg.ExpertDecision,
		arg.FinalActionID,
	)
	var i DecisionTrace
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.Step,
		&i.Timestamp,
		&i.DataSnapshot,
		&i.ModelVersion,
		&i.Parameters,
		&i.Risk,
		&i.ExpertDecision,
		&i.FinalActionID,
		&i.CreatedAt,
	)
	return i, err
}

const listDecisionTraceByCase = `-- name: ListDecisionTraceByCase :many
SELECT id, case_id, step, timestamp, data_snapshot, model_version, parameters, risk, expert_decision, final_action_id, created_at
FROM decision_trace
WHERE case_id = $1
ORDER BY timestamp ASC, created_at ASC
`

func (q *Queries) ListDecisionTraceByCase(ctx context.Context, caseID pgtype.UUID) ([]DecisionTrace, error) {
	rows, err := q.db.Query(ctx, listDecisionTraceByCase, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DecisionTrace
	for rows.Next() {
		var i DecisionTrace
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.Step,
			&i.Timestamp,
			&i.DataSnapshot,
			&i.ModelVersion,
			&i.Parameters,
			&i.Risk,
			&i.ExpertDecision,
			&i.FinalActionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
