// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: diagnostics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDiagnostic = `-- name: CreateDiagnostic :one
INSERT INTO diagnostics (
    case_id,
    hypothesis,
    confidence,
    details
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, case_id, hypothesis, confidence, details, created_at
`

type CreateDiagnosticParams struct {
	CaseID     pgtype.UUID    `json:"case_id"`
	Hypothesis string         `json:"hypothesis"`
	Confidence pgtype.Numeric `json:"confidence"`
	Details    []byte         `json:"details"`
}

func (q *Queries) CreateDiagnostic(ctx context.Context, arg CreateDiagnosticParams) (Diagnostic, error) {
	row := q.db.QueryRow(ctx, createDiagnostic,
		arg.CaseID,
		arg.Hypothesis,
		arg.Confidence,
		arg.Details,
	)
	var i Diagnostic
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.Hypothesis,
		&i.Confidence,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const listDiagnosticsByCase = `-- name: ListDiagnosticsByCase :many
SELECT id, case_id, hypothesis, confidence, details, created_at
FROM diagnostics
WHERE case_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDiagnosticsByCase(ctx context.Context, caseID pgtype.UUID) ([]Diagnostic, error) {
	rows, err := q.db.Query(ctx, listDiagnosticsByCase, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Diagnostic
	for rows.Next() {
		var i Diagnostic
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.Hypothesis,
			&i.Confidence,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
