// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    case_id,
    occurred_at,
    source,
    raw_data
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, case_id, occurred_at, source, raw_data, created_at
`

type CreateEventParams struct {
	CaseID     pgtype.UUID        `json:"case_id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	Source     string             `json:"source"`
	RawData    []byte             `json:"raw_data"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.CaseID,
		arg.OccurredAt,
		arg.Source,
		arg.RawData,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.OccurredAt,
		&i.Source,
		&i.RawData,
		&i.CreatedAt,
	)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, case_id, occurred_at, source, raw_data, created_at
FROM events
WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.OccurredAt,
		&i.Source,
		&i.RawData,
		&i.CreatedAt,
	)
	return i, err
}

const listEventsByCase = `-- name: ListEventsByCase :many
SELECT id, case_id, occurred_at, source, raw_data, created_at
FROM events
WHERE case_id = $1
ORDER BY occurred_at DESC, created_at DESC
`

func (q *Queries) ListEventsByCase(ctx context.Context, caseID pgtype.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByCase, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.OccurredAt,
			&i.Source,
			&i.RawData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
