// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kpi.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createKPI = `-- name: CreateKPI :one
INSERT INTO kpi (
    code,
    name,
    target_value,
    lower_bound,
    upper_bound,
    weight,
    unit,
    description
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, code, name, target_value, lower_bound, upper_bound, weight, unit, description, created_at
`

type CreateKPIParams struct {
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	TargetValue pgtype.Numeric `json:"target_value"`
	LowerBound  pgtype.Numeric `json:"lower_bound"`
	UpperBound  pgtype.Numeric `json:"upper_bound"`
	Weight      pgtype.Numeric `json:"weight"`
	Unit        pgtype.Text    `json:"unit"`
	Description pgtype.Text    `json:"description"`
}

func (q *Queries) CreateKPI(ctx context.Context, arg CreateKPIParams) (Kpi, error) {
	row := q.db.QueryRow(ctx, createKPI,
		arg.Code,
		arg.Name,
		arg.TargetValue,
		arg.LowerBound,
		arg.UpperBound,
		arg.Weight,
		arg.Unit,
		arg.Description,
	)
	var i Kpi
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.TargetValue,
		&i.LowerBound,
		&i.UpperBound,
		&i.Weight,
		&i.Unit,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteKPI = `-- name: DeleteKPI :exec
DELETE FROM kpi
WHERE id = $1
`

func (q *Queries) DeleteKPI(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteKPI, id)
	return err
}

const getKPI = `-- name: GetKPI :one
SELECT id, code, name, target_value, lower_bound, upper_bound, weight, unit, description, created_at
FROM kpi
WHERE id = $1
`

func (q *Queries) GetKPI(ctx context.Context, id pgtype.UUID) (Kpi, error) {
	row := q.db.QueryRow(ctx, getKPI, id)
	var i Kpi
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.TargetValue,
		&i.LowerBound,
		&i.UpperBound,
		&i.Weight,
		&i.Unit,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listKPI = `-- name: ListKPI :many
SELECT id, code, name, target_value, lower_bound, upper_bound, weight, unit, description, created_at
FROM kpi
ORDER BY code
`

func (q *Queries) ListKPI(ctx context.Context) ([]Kpi, error) {
	rows, err := q.db.Query(ctx, listKPI)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Kpi
	for rows.Next() {
		var i Kpi
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.TargetValue,
			&i.LowerBound,
			&i.UpperBound,
			&i.Weight,
			&i.Unit,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKPI = `-- name: UpdateKPI :one
UPDATE kpi
SET
    code = $2,
    name = $3,
    target_value = $4,
    lower_bound = $5,
    upper_bound = $6,
    weight = $7,
    unit = $8,
    description = $9
WHERE id = $1
RETURNING id, code, name, target_value, lower_bound, upper_bound, weight, unit, description, created_at
`

type UpdateKPIParams struct {
	ID          pgtype.UUID    `json:"id"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	TargetValue pgtype.Numeric `json:"target_value"`
	LowerBound  pgtype.Numeric `json:"lower_bound"`
	UpperBound  pgtype.Numeric `json:"upper_bound"`
	Weight      pgtype.Numeric `json:"weight"`
	Unit        pgtype.Text    `json:"unit"`
	Description pgtype.Text    `json:"description"`
}

func (q *Queries) UpdateKPI(ctx context.Context, arg UpdateKPIParams) (Kpi, error) {
	row := q.db.QueryRow(ctx, updateKPI,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.TargetValue,
		arg.LowerBound,
		arg.UpperBound,
		arg.Weight,
		arg.Unit,
		arg.Description,
	)
	var i Kpi
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.TargetValue,
		&i.LowerBound,
		&i.UpperBound,
		&i.Weight,
		&i.Unit,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
