// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kpi_snapshots.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createKPISnapshot = `-- name: CreateKPISnapshot :one
INSERT INTO kpi_snapshots (
    case_id,
    kpi_id,
    planned,
    actual,
    deviation
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, case_id, kpi_id, planned, actual, deviation, created_at
`

type CreateKPISnapshotParams struct {
	CaseID    pgtype.UUID    `json:"case_id"`
	KpiID     pgtype.UUID    `json:"kpi_id"`
	Planned   pgtype.Numeric `json:"planned"`
	Actual    pgtype.Numeric `json:"actual"`
	Deviation pgtype.Numeric `json:"deviation"`
}

func (q *Queries) CreateKPISnapshot(ctx context.Context, arg CreateKPISnapshotParams) (KpiSnapshot, error) {
	row := q.db.QueryRow(ctx, createKPISnapshot,
		arg.CaseID,
		arg.KpiID,
		arg.Planned,
		arg.Actual,
		arg.Deviation,
	)
	var i KpiSnapshot
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.KpiID,
		&i.Planned,
		&i.Actual,
		&i.Deviation,
		&i.CreatedAt,
	)
	return i, err
}

const listKPISnapshotsByCase = `-- name: ListKPISnapshotsByCase :many
SELECT id, case_id, kpi_id, planned, actual, deviation, created_at
FROM kpi_snapshots
WHERE case_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListKPISnapshotsByCase(ctx context.Context, caseID pgtype.UUID) ([]KpiSnapshot, error) {
	rows, err := q.db.Query(ctx, listKPISnapshotsByCase, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KpiSnapshot
	for rows.Next() {
		var i KpiSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.KpiID,
			&i.Planned,
			&i.Actual,
			&i.Deviation,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
