// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Case struct {
	ID               pgtype.UUID        `json:"id"`
	Status           string             `json:"status"`
	RiskLevel        pgtype.Text        `json:"risk_level"`
	SelectedActionID pgtype.UUID        `json:"selected_action_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type CorrectiveAction struct {
	ID                  pgtype.UUID        `json:"id"`
	CaseID              pgtype.UUID        `json:"case_id"`
	Code                pgtype.Text        `json:"code"`
	Description         string             `json:"description"`
	ActionType          string             `json:"action_type"`
	ExpectedLoss        pgtype.Numeric     `json:"expected_loss"`
	VarValue            pgtype.Numeric     `json:"var_value"`
	CvarValue           pgtype.Numeric     `json:"cvar_value"`
	ConstraintsViolated []byte             `json:"constraints_violated"`
	IsSelected          bool               `json:"is_selected"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type DecisionTrace struct {
	ID             pgtype.UUID        `json:"id"`
	CaseID         pgtype.UUID        `json:"case_id"`
	Step           string             `json:"step"`
	Timestamp      pgtype.Timestamptz `json:"timestamp"`
	DataSnapshot   []byte             `json:"data_snapshot"`
	ModelVersion   pgtype.Text        `json:"model_version"`
	Parameters     []byte             `json:"parameters"`
	Risk           []byte             `json:"risk"`
	ExpertDecision []byte             `json:"expert_decision"`
	FinalActionID  pgtype.UUID        `json:"final_action_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Diagnostic struct {
	ID         pgtype.UUID        `json:"id"`
	CaseID     pgtype.UUID        `json:"case_id"`
	Hypothesis string             `json:"hypothesis"`
	Confidence pgtype.Numeric     `json:"confidence"`
	Details    []byte             `json:"details"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Event struct {
	ID         pgtype.UUID        `json:"id"`
	CaseID     pgtype.UUID        `json:"case_id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	Source     string             `json:"source"`
	RawData    []byte             `json:"raw_data"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Experiment struct {
	ID        pgtype.UUID        `json:"id"`
	RunAt     pgtype.Timestamptz `json:"run_at"`
	Mode      string             `json:"mode"`
	Metrics   []byte             `json:"metrics"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ExperimentResult struct {
	ID              pgtype.UUID        `json:"id"`
	ExperimentID    pgtype.UUID        `json:"experiment_id"`
	CaseID          pgtype.UUID        `json:"case_id"`
	Mode            string             `json:"mode"`
	KpiDeviation    pgtype.Numeric     `json:"kpi_deviation"`
	Cvar            pgtype.Numeric     `json:"cvar"`
	Violations      int32              `json:"violations"`
	Reproducibility pgtype.Numeric     `json:"reproducibility"`
	Metrics         []byte             `json:"metrics"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Kpi struct {
	ID          pgtype.UUID        `json:"id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	TargetValue pgtype.Numeric     `json:"target_value"`
	LowerBound  pgtype.Numeric     `json:"lower_bound"`
	UpperBound  pgtype.Numeric     `json:"upper_bound"`
	Weight      pgtype.Numeric     `json:"weight"`
	Unit        pgtype.Text        `json:"unit"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type KpiSnapshot struct {
	ID        pgtype.UUID        `json:"id"`
	CaseID    pgtype.UUID        `json:"case_id"`
	KpiID     pgtype.UUID        `json:"kpi_id"`
	Planned   pgtype.Numeric     `json:"planned"`
	Actual    pgtype.Numeric     `json:"actual"`
	Deviation pgtype.Numeric     `json:"deviation"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Scenario struct {
	ID          pgtype.UUID        `json:"id"`
	CaseID      pgtype.UUID        `json:"case_id"`
	Name        string             `json:"name"`
	Probability pgtype.Numeric     `json:"probability"`
	LossVector  []byte             `json:"loss_vector"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
