// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scenarios.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScenario = `-- name: CreateScenario :one
INSERT INTO scenarios (
    case_id,
    name,
    probability,
    loss_vector
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, case_id, name, probability, loss_vector, created_at
`

type CreateScenarioParams struct {
	CaseID      pgtype.UUID    `json:"case_id"`
	Name        string         `json:"name"`
	Probability pgtype.Numeric `json:"probability"`
	LossVector  []byte         `json:"loss_vector"`
}

func (q *Queries) CreateScenario(ctx context.Context, arg CreateScenarioParams) (Scenario, error) {
	row := q.db.QueryRow(ctx, createScenario,
		arg.CaseID,
		arg.Name,
		arg.Probability,
		arg.LossVector,
	)
	var i Scenario
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.Name,
		&i.Probability,
		&i.LossVector,
		&i.CreatedAt,
	)
	return i, err
}

const listScenariosByCase = `-- name: ListScenariosByCase :many
SELECT id, case_id, name, probability, loss_vector, created_at
FROM scenarios
WHERE case_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListScenariosByCase(ctx context.Context, caseID pgtype.UUID) ([]Scenario, error) {
	rows, err := q.db.Query(ctx, listScenariosByCase, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scenario
	for rows.Next() {
		var i Scenario
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.Name,
			&i.Probability,
			&i.LossVector,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
