.PHONY: verify test run
verify:
	python3 tools/verify_sources.py
test: verify
	cd engine && go test -race ./...
	cd backend && go test -race ./...
	cd engine && go vet ./...
	cd backend && go vet ./...
	cd frontend && npm run typecheck
run:
	python3 tools/run.py
